main*:
  build_and_deploy_docs:
    - docker:
        image: node:22
        #volumes缓存：https://docs.cnb.cool/grammar/pipeline.html#volumes
        volumes:
          - /root/.npm:cow

      imports: 
        - https://cnb.cool/wangcaiyuan/private-key/-/blob/main/ssh.yml

      stages:
        - name: 安装依赖
          script: npm install && npm run docs:build

        - name: 查看目录
          script: ls -a

        - name: 部署文档
          image: tencentcom/rsync
          settings:
            host: $DEVELOP_HOST
            user: $DEVELOP_USERNAME
            port: $DEVELOP_PORT
            key: $DEVELOP_KEY
            source: ./docs/.vitepress/dist
            target: /opt/1panel/www/sites/translator.wangcaiyuan.com/index
